dist: trusty
sudo: false

language: python
notifications:
    email: false
cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=dynetlsm
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.7"
      NUMPY_VERSION="1.18.1" SCIPY_VERSION="1.4.1" CYTHON_VERSION="0.29.14"

install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: joshloyal
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: joshloyal/dynetlsm
