build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

matrix:
    fast_finish: true

install:
  # Prepend miniconda installed Python to the PATH of this build
  # Add Library/bin directory to fix issue
  # https://github.com/conda/conda/issues/1753
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - conda install pip scipy numpy scikit-learn=0.22.1 cython -y -q
  - conda install pytest pytest-cov -y -q
  - pip install .

test_script:
  - mkdir for_test
  - cd for_test
  - pytest --pyargs
